force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <nameField>
        <label>Reservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Room</fullName>
            </value>
            <value>
                <fullName>Equipment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReservationTriggerHandlerTest.cls
@isTest
public class ReservationTriggerHandlerTest {
    @TestSetup
    static void setup() {
        System.runAs(TestHelper.createAdminUser()) {
            insert new List<Resource__c>{
                new Resource__c(Name = 'RoomResource', Type__c = 'Room'),
                new Resource__c(Name = 'EquipmentResource', Type__c = 'Equipment')
            };

            TestHelper.createContact('lastName', 'example@email.com');
        }
    }

    @isTest
    static void shouldPopulateNameOnInsert() {
        System.runAs(TestHelper.getAdminUser()) {
            Contact con = [SELECT Id, Name FROM Contact LIMIT 1];
            Resource__c res = [SELECT Id, Name FROM Resource__c WHERE Name = 'RoomResource' LIMIT 1];

            Reservation__c newReservation = new Reservation__c(
                Contact__c = con.Id,
                Resource__c = res.Id,
                Start_date__c = Date.today(),
                End_date__c = Date.today().addDays(2)
            );
            Test.startTest();

            insert newReservation;

            Test.stopTest();

            Reservation__c updatedRes = [SELECT Name FROM Reservation__c WHERE Id = :newReservation.Id];

            Assert.isTrue(updatedRes.Name.contains('lastName'), 'Name should contain Contact Name');
            Assert.isTrue(updatedRes.Name.contains('RoomResource'), 'Name should contain Resource Name');
        }
    }
}