force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <nameField>
        <label>Reservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/tmpreservationHelper.cls
public inherited sharing class ReservationHelper {
    public static List<Date> getBookedDates(Id resourceId) {
        List<Date> bookedDates = new List<Date>();
        for (Reservation__c res : [
            SELECT Start_date__c, End_date__c
            FROM Reservation__c
            WHERE Resource__c = :resourceId AND End_date__c >= TODAY
        ]) {
            Date currentDate = res.Start_date__c;
            while (currentDate <= res.End_date__c) {
                bookedDates.add(currentDate);
                currentDate = currentDate.addDays(1);
            }
        }
        return bookedDates;
    }
}