force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <nameField>
        <label>Reservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Under repair</fullName>
            </value>
            <value>
                <fullName>Free</fullName>
                <default>true</default>
                <label>Free</label>
            </value>
            <value>
                <fullName>In use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/createReservationController.cls
public with sharing class createReservationController {
    @AuraEnabled(cacheable=true)
    public static Id getContact(String lastName, String email) {
        try {
            return [SELECT Id, lastName, Email FROM Contact WHERE Email = :email AND lastName = :lastName LIMIT 1].Id;
        } catch (QueryException e) {
            if (e.getMessage().contains('List has no rows for assignment to SObject')) {
                return null;
            } else {
                System.debug(LoggingLevel.ERROR, 'Error retrieving contact: ' + e.getMessage());
                throw new AuraHandledException('Error retrieving contact: ' + e.getMessage());
            }
        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR, 'Error retrieving contact: ' + e.getMessage());
            throw new AuraHandledException('Error retrieving contact: ' + e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<createReservationHelper.Option> getResources() {
        try {
            List<createReservationHelper.Option> options = new List<createReservationHelper.Option>();
            for (Resource__c res : [SELECT Id, Name FROM Resource__c WHERE Status__c = 'Free']) {
                options.add(new createReservationHelper.Option(res.Name, res.Id));
            }
            return options;
        } catch (QueryException e) {
            if (e.getMessage().contains('List has no rows for assignment to SObject')) {
                return new List<createReservationHelper.Option>();
            } else {
                System.debug(LoggingLevel.ERROR, 'Error during retrieval of resources: ' + e.getMessage());
                throw new AuraHandledException('Error retrieving resources: ' + e.getMessage());
            }
        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR, 'Error during retrieval of resources: ' + e.getMessage());
            throw new AuraHandledException('Error retrieving resources: ' + e.getMessage());
        }
    }

    @AuraEnabled
    public static void createReservation(Id contactId, Id resourceId, Date startDate, Date endDate) {
        try {
            insert new Reservation__c(Contact__c = contactId, Resource__c = resourceId, Start_date__c = startDate, End_date__c = endDate);
        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR, 'Error during creation of reservation: ' + e.getMessage());
            throw new AuraHandledException('An error occurred during creation of reservation: ' + e.getMessage());
        }
    }

    public static Map<Id, List<createReservationHelper.ReservationRange>> getReservationRanges() {
        Map<Id, List<createReservationHelper.ReservationRange>> reservationMap = new Map<Id, List<createReservationHelper.ReservationRange>>();
        for (Reservation__c res : [SELECT Id, Resource__c, Start_date__c, End_date__c FROM Reservation__c]) {
            if (!reservationMap.containsKey(res.Resource__c)) {
                reservationMap.put(res.Resource__c, new List<createReservationHelper.ReservationRange>());
            }
            reservationMap.get(res.Resource__c).add(new createReservationHelper.ReservationRange(res.Start_date__c, res.End_date__c));
        }
        return reservationMap;
    }
}